#ifndef _BLOCK_PROTO_H_
#define _BLOCK_PROTO_H_

#include "block_boot.h"

#define BLOCK_SERVICE_NAME "block"
#define BLOCK_SECTOR_SIZE 512ULL
#define BLOCK_VIRTIO_MMIO_VA BLOCK_DEVICE_MMIO_VA
#define BLOCK_VIRTIO_MMIO_SIZE BLOCK_DEVICE_MMIO_SIZE

#define BLOCK_REQ_READ 1
#define BLOCK_REQ_WRITE 2

#endif
