#ifndef _BLOCK_PROTO_H_
#define _BLOCK_PROTO_H_

#define BLOCK_SERVICE_NAME "block"
#define BLOCK_SECTOR_SIZE 512ULL
#define BLOCK_VIRTIO_MMIO_VA 0xB0010000ULL
#define BLOCK_VIRTIO_MMIO_PA 0x0A000000ULL
#define BLOCK_VIRTIO_MMIO_SIZE 0x4000ULL

#define BLOCK_REQ_READ 1
#define BLOCK_REQ_WRITE 2

#endif
