#pragma once

#include "display_proto.h"

#define COMPOSITOR_REQ_INFO           1ULL
#define COMPOSITOR_REQ_CREATE_SURFACE 2ULL
#define COMPOSITOR_REQ_DAMAGE_SURFACE 3ULL
#define COMPOSITOR_REQ_MOVE_SURFACE   4ULL
#define COMPOSITOR_REQ_DESTROY_SURFACE 5ULL
#define COMPOSITOR_REQ_STATS          6ULL
#define COMPOSITOR_REQ_RESET_STATS    7ULL
#define COMPOSITOR_REQ_SET_SURFACE_FLAGS 8ULL
#define COMPOSITOR_REQ_POLL_EVENT     9ULL

#define COMPOSITOR_ABI_VERSION 1ULL

#define COMPOSITOR_SURFACE_FLAG_FOCUSABLE (1ULL << 0)
#define COMPOSITOR_SURFACE_FLAG_CHROME    (1ULL << 1)
#define COMPOSITOR_SURFACE_FLAG_RESIZABLE (1ULL << 2)

#define COMPOSITOR_EVENT_POINTER_MOVE 1ULL
#define COMPOSITOR_EVENT_POINTER_DOWN 2ULL
#define COMPOSITOR_EVENT_POINTER_UP   3ULL
#define COMPOSITOR_EVENT_FOCUS        4ULL
#define COMPOSITOR_EVENT_CLOSE        5ULL
#define COMPOSITOR_EVENT_RESIZE       6ULL

#define COMPOSITOR_MAX_SURFACES 16U
